### ISSUE TITLE
NeoForge 1.21.1 | java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1944

### ISSUE THREAD

**Issue by JohnGoten** [nthxny/SatisfyingButtons#7]
- NeoForge 21.1.61
- Satisfying Buttons 1.1.2 (still recognized by Prism as 1.1.1 but file is the current latest)
- running Prism Launcher 8.4 and Adoptium Eclipse Temurin 21.0.4

Using only the Satisfying Buttons mod in an isolated instance, attempting to join a world after entering it once - either just created or pre-existing - the user is met with an ArrayIndexOutOfBoundsException error on screen and sent directly to the multiplayer menu.
I can replicate this behavior consistently. https://mclo.gs/V198n5R
![2024-09-27_16 21 37](https://github.com/user-attachments/assets/921cbcf0-017d-4266-9a9b-c4e53b0331cb)

**Comment by JohnGoten** [comment]
Months have passed.
I waited for long until I realized this project is related to LunaPixelStudios. Ever since then I refuse to touch this garbage.
No need to address this critical issue given how there appears to be nobody around to care anyway.

Screw you!

**Comment by txnitxnichopper** [comment]
hello @sharkie where is my luna pixel paycheck ...
